# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  perfumegptapi:
    build:
      context: .
      dockerfile: PerfumeGPT.API/Dockerfile
    ports:
      - 5141:5141
      - 7011:7011
    env_file:
      - .env 
